#!/bin/bash

if [ "$ES_PORT" != "" ] ; then
	# This container has been linked to an elasticsearch container, just set the bind_host in logstash conf
	sed -i "/elasticsearch {/a bind_host => \"$ES_PORT_9200_TCP_ADDR\"" /etc/logstash/conf.d/agent.conf
else
	# Update logstash eleasticsearch config so it uses ec2 discovery
	cat >> /etc/elasticsearch/elasticsearch.yml << EOF
network.publish_host: _ec2_

cloud:
  aws:
    region: $ES_AWS_REGION

discovery:
  type: ec2
  ec2:
    groups: $ES_CLUSTER_NAME
EOF
fi
export LS_HEAP_SIZE=500m
export LS_JAVA_OPTS=-Djava.va.io.tmpdir=/var/lib/logstash
/opt/logstash/bin/logstash agent -f /etc/logstash/conf.d/agent.conf -l /var/hostlogs/logstash/logstash.log $LOGSTASH_OPTS
