#!/bin/bash

cat >> /etc/elasticsearch/elasticsearch.yml << EOF
cluster.name: $ES_CLUSTER_NAME
EOF

if [ "$ES_DISCOVERY" == "ec2" ] ; then
	# Update logstash eleasticsearch config so it uses ec2 discovery
	cat >> /etc/elasticsearch/elasticsearch.yml << EOF
network.publish_host: _ec2_

cloud:
  aws:
    region: $ES_AWS_REGION

discovery:
  type: ec2
  ec2:
    groups: $ES_CLUSTER_NAME
EOF
fi
export LS_HEAP_SIZE=500m
export LS_JAVA_OPTS=-Djava.va.io.tmpdir=/var/lib/logstash
/opt/logstash/bin/logstash agent -f /etc/logstash/conf.d/agent.conf -l /var/host/log/logstash/logstash.log $LOGSTASH_OPTS
